//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tizen.VisualStudio.ViewAndUI.InstallLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallWizardString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallWizardString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tizen.VisualStudio.ViewAndUI.InstallLauncher.InstallWizardString", typeof(InstallWizardString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree.
        /// </summary>
        public static string Button_Agree {
            get {
                return ResourceManager.GetString("Button_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string Button_Back {
            get {
                return ResourceManager.GetString("Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Button_Finish {
            get {
                return ResourceManager.GetString("Button_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Button_Install {
            get {
                return ResourceManager.GetString("Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install new TizenSDK
        ///- You can install.
        /// </summary>
        public static string Button_NewInstall {
            get {
                return ResourceManager.GetString("Button_NewInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string Button_Next {
            get {
                return ResourceManager.GetString("Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISUAL STUDIO TOOLS FOR TIZEN LICENSE AGREEMENT
        ///
        ///BEFORE YOU (&quot;YOU&quot; OR &quot;LICENSEE&quot;) USE THE VISUAL STUDIO TOOLS FOR TIZEN, PLEASE READ ALL OF THE TERMS AND CONDITIONS SET OUT IN THIS VISUAL STUDIO TOOLS FOR TIZEN LICENSE AGREEMENT (&quot;AGREEMENT&quot;) CAREFULLY. YOUR USE OF THE VISUAL STUDIO TOOLS FOR TIZEN IS SUBJECT TO THE TERMS AND CONDITIONS SET FORTH IN THIS AGREEMENT. BY SELECTING &quot;I ACCEPT THE TERMS IN THE LICENSE AGREEMENT&quot; AND CLICKING &quot;NEXT&quot; BUTTON OR BY USING ANY PART OF THE VISUAL STUDIO TOOLS FOR TIZE [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EULASTRING {
            get {
                return ResourceManager.GetString("EULASTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the path for Tizen SDK.
        /// </summary>
        public static string Label_BASEWARN {
            get {
                return ResourceManager.GetString("Label_BASEWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is not empty.
        /// </summary>
        public static string Label_DirEmptyWARN {
            get {
                return ResourceManager.GetString("Label_DirEmptyWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is not exist.
        /// </summary>
        public static string Label_DirExistWARN {
            get {
                return ResourceManager.GetString("Label_DirExistWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected directory is not empty.
        /// </summary>
        public static string Label_EMPTYWARN {
            get {
                return ResourceManager.GetString("Label_EMPTYWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK tools are not detected, You can install it or set tools path..
        /// </summary>
        public static string Label_FirstScreen {
            get {
                return ResourceManager.GetString("Label_FirstScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizen SDK Installer is downloading....
        /// </summary>
        public static string Label_FourthScreen_New {
            get {
                return ResourceManager.GetString("Label_FourthScreen_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java Runtime Environment is not detected, Install process may not proceed..
        /// </summary>
        public static string Label_JREWARN {
            get {
                return ResourceManager.GetString("Label_JREWARN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizen SDK Installer.
        /// </summary>
        public static string Label_Main {
            get {
                return ResourceManager.GetString("Label_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select root directory for installed Tizen SDK.
        /// </summary>
        public static string Label_SecondScreen_Exist {
            get {
                return ResourceManager.GetString("Label_SecondScreen_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install new Tizen SDK, Please review below EULA..
        /// </summary>
        public static string Label_SecondScreen_New {
            get {
                return ResourceManager.GetString("Label_SecondScreen_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an empty folder to install.
        /// </summary>
        public static string Label_ThirdScreen {
            get {
                return ResourceManager.GetString("Label_ThirdScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Tizen SDK version is low, please update the Tizen SDK.
        /// </summary>
        public static string Label_VERWARN {
            get {
                return ResourceManager.GetString("Label_VERWARN", resourceCulture);
            }
        }
    }
}
